### ISSUE TITLE
error: This vue app/component has no vue-meta configuration

### ISSUE THREAD

**Issue by LemonAppleMo** [vapperjs/vapper#11]
使用vapper/examples/vue-cli3/ 这个代码示例，运行监听localhost:4000，当访问的时候，在终端会出现“This vue app/component has no vue-meta configuration
Server rendering encountered an error: { TypeError: Cannot read property 'text' of undefined”这个报错。然后会提示，退回SPA模式“Will fall back SPA mode, url is: /foo/bar”

![image](https://user-images.githubusercontent.com/32638462/66710186-17227900-eda6-11e9-90d8-afac20510226.png)

**Comment by HcySunYang** [comment]
你是如何使用的这个 vapper/examples/vue-cli3/ 示例的？把你的步骤说一下。你可以按照官网的教程一步一步搭建也是很轻松的。

**Comment by LemonAppleMo** [comment]
我不知道是不是我全局配置的问题，我按照官网的来也会报错。具体操作步骤就是把这个代码download下来，然后yarn install，再yarn add @vapper/core ，最后再使用yarn dev命令启动

**Comment by LemonAppleMo** [comment]
![image](https://user-images.githubusercontent.com/32638462/66712376-7a280600-edce-11e9-8bc7-e5eff456e6fb.png)
![image](https://user-images.githubusercontent.com/32638462/66712379-801de700-edce-11e9-8e06-dcc5cb81864b.png)
直接复制粘贴官网上的，然后还是会报错。

![image](https://user-images.githubusercontent.com/32638462/66712398-aba0d180-edce-11e9-8b67-8dcb12f307e1.png)

vue 的版本
![image](https://user-images.githubusercontent.com/32638462/66712409-c2472880-edce-11e9-90d0-201547a9b18d.png)
我找不出是什么原因导致的报错

**Comment by HcySunYang** [comment]
从图片来看，你的服务已经启动成功了，你的报错信息是因为”Cannot read property 'text' of undefined“。

**Comment by LemonAppleMo** [comment]
![image](https://user-images.githubusercontent.com/32638462/66713864-232c2c00-ede2-11e9-81d2-7373839b60d1.png)
我看到index.template.html里面有这些关键字，不知道会不会和这个有关系。因为我没有使用text这个key。
包括下面lodash.template/index也报错了。会不会和这里有关系呢。我这个项目就是用vue cretae出来，然后按照官网一步一步来的。

**Comment by LemonAppleMo** [comment]
看来就是这个原因
![image](https://user-images.githubusercontent.com/32638462/66714109-355b9980-ede5-11e9-8022-053bbfd93aad.png)
![image](https://user-images.githubusercontent.com/32638462/66714107-2e348b80-ede5-11e9-8786-66e69f3fce32.png)

**Comment by LemonAppleMo** [comment]
还原回去的话，就自动转为SPA了
![image](https://user-images.githubusercontent.com/32638462/66714125-7bb0f880-ede5-11e9-96c9-23cba242129b.png)
![image](https://user-images.githubusercontent.com/32638462/66714127-7eabe900-ede5-11e9-8b29-6db3c3e456e8.png)
![image](https://user-images.githubusercontent.com/32638462/66714141-9a16f400-ede5-11e9-8a7c-31b01dba25ee.png)

**Comment by LemonAppleMo** [comment]
我这样修改了一下

![image](https://user-images.githubusercontent.com/32638462/66714222-cb43f400-ede6-11e9-9743-0c6aaa3e832e.png)

**Comment by HcySunYang** [comment]
我知道什么原因了，vue-meta 更新的原因，现在要求必须使用 vue-meta 的配置选项，你可以在根组件中加上：`head: {}` 就可以了，如下：
```js
const app = new Vue({
    router,
    head: {},
    render: h => h(App)
})
```

**Comment by HcySunYang** [comment]
我后面会补充一下 examples

**Comment by LemonAppleMo** [comment]
好的
