### ISSUE TITLE
按照官网步骤操作的，vuecli3创建的初始项目，运行起来服务端渲染报错，是哪没配好么

### ISSUE THREAD

**Issue by fengfengyouyou** [vapperjs/vapper#12]
![image](https://user-images.githubusercontent.com/51188871/67355299-84de5a00-f589-11e9-9204-4a7c626bcbfd.png)

错误信息：
debug Server rendering encountered an error: { TypeError: Cannot read property '
text' of undefined

**Comment by HcySunYang** [comment]
请查看这个 issue: https://github.com/vapperjs/vapper/issues/11
